name: Acceptance Stage
on:
  workflow_run:
    workflows: ["Commit Stage"]
    types: [completed]
    branches: master
concurrency: acceptance

jobs:
  acceptance-stage:
    uses: andrei-lupsa/polar-deployment/.github/workflows/acceptance-stage.yml@master
